### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by jgroom33** [eykhagen/strest#25]
Use Environment Variables to replace `{{}}`
```yml
version: 1                            # only version at the moment
requests:                             # all test requests will be listed here
  foo:
    url: "{{MY_ENV_VAR}}/api/v1/bar"
    method: GET                       # required
```
