### ISSUE TITLE
Repeat until

### ISSUE THREAD

**Issue by jgroom33** [eykhagen/strest#30]
Repeat a request until a criteria is met.

```yml
requests:
  userRequest:
    url: http://localhost:3001/user 
    method: GET
    data:
      params:
        name: testUser
    max_retries: 3
    delay: 3000
    validate:
      json:
        somethingCompleted: "true"
```

The above request executes a maximum of 3 times before the failure is propagated
